# Q-A System

    Charlie Marshall
    Prof. Klabjan
    IEMS 308
    20 March 2020

In [2]:
import pandas as pd
import numpy as np
import scipy
import re
import glob
import os

from nltk.tokenize import word_tokenize,sent_tokenize,RegexpTokenizer
from nltk import pos_tag
import spacy

from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix

from nltk.corpus import stopwords
stop_words=set(stopwords.words("english"))

from imblearn.over_sampling import SMOTE
import statsmodels.api as sm

## Load in relevant info from Project 3

In [157]:
from TextAnalytics import finalCEO,ceo_final,finalCompany,comp_final,finalPercentage,perc_df_extract

ReutersChina's seven day repo rose to a record high of 10.77% in Shanghai, the highest since March 2003, according to Bloomberg*. Meanwhile, the one-day rate hit a record 12.85%. And Zerohedge reported that overnight repo hit 25%. The liquidity squeeze in China first began ahead of the Dragon Boat festival earlier this month. Spikes in interbank rates are common right before holidays.  But Diana Choyleva at Lombard Street Research said this is symptomatic of a bigger problem. She said capital flows had "become a more important driver of domestic liquidity conditions in China's managed exchange rate system." In a new note to clients Bank of America's Ting Lu wrote: "There are many factors behind the interbank liquidity squeeze that might be cited, but we believe that the ultimate reason is the central bank’s tough stance as the PBOC can practically provide unlimited liquidity to ease every squeeze if it wishes to."  Banks have been clamoring for a reserve requirement ratio cut. So w

ReutersChina's seven day repo rose to a record high of 10.77% in Shanghai, the highest since March 2003, according to Bloomberg. Meanwhile, the one-day rate hit a record 12.85%. And Zerohedge reported that overnight repo hit 25%. The liquidity squeeze in China first began ahead of the Dragon Boat festival earlier this month. Spikes in interbank rates are common right before holidays. But Diana Choyleva at Lombard Street Research said this is symptomatic of a bigger problem. She said capital flows had "become a more important driver of domestic liquidity conditions in China's managed exchange rate system." In a new note to clients Bank of America's Ting Lu wrote: "There are many factors behind the interbank liquidity squeeze that might be cited, but we believe that the ultimate reason is the central banks tough stance as the PBOC can practically provide unlimited liquidity to ease every squeeze if it wishes to." Banks have been clamoring for a reserve requirement ratio cut. So why isn't

/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


length of oversampled ceos is  434878
Number of non-CEOs in oversampled ceos 217439
Number of CEOs 217439
Proportion of non-ceos in oversampled ceos is  0.5
Proportion of ceos in oversampled ceos is  0.5


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: Futur

[False False  True False False  True  True  True  True  True  True False
  True  True  True False False  True  True False False False False  True
  True False False  True False False  True False]
[12 16  1 14 17  1  1  1  1  1  1  8  1  1  1  2 13  1  1 15  7  5  9  1
  1 11  3  1  6  4  1 10]
         Current function value: 0.638986
         Iterations: 35
         Function evaluations: 36
         Gradient evaluations: 36
                          Results: Logit
Model:              Logit            Pseudo R-squared: 0.078      
Dependent Variable: label            AIC:              555793.5278
Date:               2020-03-15 03:42 BIC:              555969.2529
No. Observations:   434878           Log-Likelihood:   -2.7788e+05
Df Model:           15               LL-Null:          -3.0143e+05
Df Residuals:       434862           LLR p-value:      0.0000     
Converged:          0.0000           Scale:            1.0000     
-------------------------------------------------------------

/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


         Current function value: 0.639072
         Iterations: 35
         Function evaluations: 36
         Gradient evaluations: 36
                          Results: Logit
Model:              Logit            Pseudo R-squared: 0.078      
Dependent Variable: label            AIC:              555856.7887
Date:               2020-03-15 03:42 BIC:              555966.6169
No. Observations:   434878           Log-Likelihood:   -2.7792e+05
Df Model:           9                LL-Null:          -3.0143e+05
Df Residuals:       434868           LLR p-value:      0.0000     
Converged:          0.0000           Scale:            1.0000     
-------------------------------------------------------------------
              Coef.   Std.Err.      z      P>|z|    [0.025   0.975]
-------------------------------------------------------------------
caps         -0.1569    0.0014  -111.0667  0.0000  -0.1596  -0.1541
ceos_two      2.4907    0.0526    47.3355  0.0000   2.3876   2.5939
pres_two      1.

/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy of logistic regression classifier on test set: 0.60
[[ 26054  82924]
 [  3107 105354]]
              precision    recall  f1-score   support

           0       0.89      0.24      0.38    108978
           1       0.56      0.97      0.71    108461

   micro avg       0.60      0.60      0.60    217439
   macro avg       0.73      0.61      0.54    217439
weighted avg       0.73      0.60      0.54    217439

         Current function value: 0.666609
         Iterations: 35
         Function evaluations: 39
         Gradient evaluations: 39
                          Results: Logit
Model:              Logit            Pseudo R-squared: 0.038      
Dependent Variable: label            AIC:              579796.9241
Date:               2020-03-15 03:42 BIC:              579851.8382
No. Observations:   434878           Log-Likelihood:   -2.8989e+05
Df Model:           4                LL-Null:          -3.0143e+05
Df Residuals:       434873           LLR p-value:      0.0000     


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy of logistic regression classifier on test set: 0.57
[[107546   1432]
 [ 91380  17081]]
              precision    recall  f1-score   support

           0       0.54      0.99      0.70    108978
           1       0.92      0.16      0.27    108461

   micro avg       0.57      0.57      0.57    217439
   macro avg       0.73      0.57      0.48    217439
weighted avg       0.73      0.57      0.48    217439



/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of logistic regression classifier on test set: 0.97
[[217028    435]
 [  7230    510]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98    217463
           1       0.54      0.07      0.12      7740

   micro avg       0.97      0.97      0.97    225203
   macro avg       0.75      0.53      0.55    225203
weighted avg       0.95      0.97      0.95    225203

Accuracy of logistic regression classifier on entire data: 0.27
[[105440 329462]
 [   305  15198]]
              precision    recall  f1-score   support

           0       1.00      0.24      0.39    434902
           1       0.04      0.98      0.08     15503

   micro avg       0.27      0.27      0.27    450405
   macro avg       0.52      0.61      0.24    450405
weighted avg       0.96      0.27      0.38    450405

Accuracy of logistic regression classifier on entire data: 0.96
[[429171   5731]
 [ 13742   1761]]
              precision    recall  f1-score   suppor

/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


                          Results: Logit
Model:              Logit            Pseudo R-squared: -0.014     
Dependent Variable: label            AIC:              352090.6038
Date:               2020-03-15 03:42 BIC:              352259.5225
No. Observations:   574498           Log-Likelihood:   -1.7603e+05
Df Model:           14               LL-Null:          -1.7359e+05
Df Residuals:       574483           LLR p-value:      1.0000     
Converged:          0.0000           Scale:            1.0000     
------------------------------------------------------------------
                  Coef.  Std.Err.     z     P>|z|   [0.025  0.975]
------------------------------------------------------------------
comp_in_sent      0.5852   0.0181   32.3502 0.0000  0.5497  0.6206
stock             0.3112   0.0201   15.4841 0.0000  0.2718  0.3506
shares            0.6558   0.0197   33.2636 0.0000  0.6172  0.6945
trade             0.0164   0.0215    0.7588 0.4479 -0.0259  0.0586
length            0.0

/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


                          Results: Logit
Model:              Logit            Pseudo R-squared: -0.014     
Dependent Variable: label            AIC:              352092.0574
Date:               2020-03-15 03:43 BIC:              352204.6699
No. Observations:   574498           Log-Likelihood:   -1.7604e+05
Df Model:           9                LL-Null:          -1.7359e+05
Df Residuals:       574488           LLR p-value:      1.0000     
Converged:          0.0000           Scale:            1.0000     
------------------------------------------------------------------
                  Coef.  Std.Err.     z     P>|z|   [0.025  0.975]
------------------------------------------------------------------
comp_in_sent      0.5845   0.0179   32.6366 0.0000  0.5494  0.6196
stock             0.3114   0.0200   15.5381 0.0000  0.2721  0.3507
shares            0.6557   0.0197   33.3204 0.0000  0.6171  0.6942
length            0.0682   0.0016   43.4091 0.0000  0.0651  0.0713
plural           -0.0

/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of logistic regression classifier on test set: 0.91
[[522252    631]
 [ 51019    596]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95    522883
           1       0.49      0.01      0.02     51615

   micro avg       0.91      0.91      0.91    574498
   macro avg       0.70      0.51      0.49    574498
weighted avg       0.87      0.91      0.87    574498



/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.

[False False  True False False False False False  True  True False  True
  True  True  True]
[2 6 1 8 9 7 3 5 1 1 4 1 1 1 1]
         Current function value: 0.684804
         Iterations: 35
         Function evaluations: 39
         Gradient evaluations: 39


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


                          Results: Logit
Model:              Logit            Pseudo R-squared: -1.266     
Dependent Variable: label            AIC:              786850.9341
Date:               2020-03-15 03:43 BIC:              786929.7629
No. Observations:   574498           Log-Likelihood:   -3.9342e+05
Df Model:           6                LL-Null:          -1.7359e+05
Df Residuals:       574491           LLR p-value:      1.0000     
Converged:          0.0000           Scale:            1.0000     
-------------------------------------------------------------------
               Coef.   Std.Err.     z      P>|z|    [0.025   0.975]
-------------------------------------------------------------------
shares        -1.4599    0.0185  -79.0546  0.0000  -1.4961  -1.4237
corp           0.5126    0.0727    7.0459  0.0000   0.3700   0.6551
group         -0.2601    0.0566   -4.5954  0.0000  -0.3710  -0.1491
inc            0.1400    0.0549    2.5502  0.0108   0.0324   0.2476
company       

/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of logistic regression classifier on test set: 0.91
[[522341    542]
 [ 50985    630]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95    522883
           1       0.54      0.01      0.02     51615

   micro avg       0.91      0.91      0.91    574498
   macro avg       0.72      0.51      0.49    574498
weighted avg       0.88      0.91      0.87    574498



/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


length of oversampled comps is  1045776
Number of non-companies in oversampled comps 522888
Number of companies 522888
Proportion of non-companies in oversampled comps is  0.5
Proportion of companies in oversampled comps is  0.5


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: Futur

[False False  True False False False False False  True  True False  True
  True  True  True]
[2 4 1 8 9 7 3 5 1 1 6 1 1 1 1]
         Current function value: 0.687099
         Iterations: 35
         Function evaluations: 39
         Gradient evaluations: 39


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


                          Results: Logit
Model:              Logit            Pseudo R-squared: 0.009       
Dependent Variable: label            AIC:              1437114.5569
Date:               2020-03-15 03:43 BIC:              1437185.7185
No. Observations:   1045776          Log-Likelihood:   -7.1855e+05 
Df Model:           5                LL-Null:          -7.2488e+05 
Df Residuals:       1045770          LLR p-value:      0.0000      
Converged:          0.0000           Scale:            1.0000      
--------------------------------------------------------------------
                Coef.   Std.Err.     z      P>|z|    [0.025   0.975]
--------------------------------------------------------------------
corp            2.4920    0.0574   43.4118  0.0000   2.3795   2.6045
group           1.7712    0.0391   45.2438  0.0000   1.6945   1.8480
inc             2.4902    0.0456   54.6467  0.0000   2.4009   2.5795
company        -1.7619    0.0982  -17.9345  0.0000  -1.9544  -1.5694


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy of logistic regression classifier on test set: 0.51
[[260649    903]
 [253798   7538]]
              precision    recall  f1-score   support

           0       0.51      1.00      0.67    261552
           1       0.89      0.03      0.06    261336

   micro avg       0.51      0.51      0.51    522888
   macro avg       0.70      0.51      0.36    522888
weighted avg       0.70      0.51      0.36    522888

Accuracy of logistic regression classifier on test set: 0.91
[[1044475    1296]
 [ 102009    1216]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95   1045771
           1       0.48      0.01      0.02    103225

   micro avg       0.91      0.91      0.91   1148996
   macro avg       0.70      0.51      0.49   1148996
weighted avg       0.87      0.91      0.87   1148996

Accuracy of logistic regression classifier on test set: 0.91
[[1044697    1074]
 [ 101988    1237]]
              precision    recall  f1-score   supp

/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of logistic regression classifier on test set: 0.62
[[158487  11678]
 [ 99369  26053]]
              precision    recall  f1-score   support

           0       0.61      0.93      0.74    170165
           1       0.69      0.21      0.32    125422

   micro avg       0.62      0.62      0.62    295587
   macro avg       0.65      0.57      0.53    295587
weighted avg       0.65      0.62      0.56    295587

Accuracy of logistic regression classifier on test set: 0.62
[[316632  23449]
 [199026  52066]]
              precision    recall  f1-score   support

           0       0.61      0.93      0.74    340081
           1       0.69      0.21      0.32    251092

   micro avg       0.62      0.62      0.62    591173
   macro avg       0.65      0.57      0.53    591173
weighted avg       0.65      0.62      0.56    591173



In [166]:
ceo_final['index']

0         1157
1         1354
2         1896
3         1980
4         1980
5         1988
6         2144
7         2148
8         2505
9         3379
10        3401
11        3408
12        3600
13        3641
14        3650
15        4034
16        4072
17        4081
18        4203
19        4204
20        4555
21        5848
22        6161
23        6293
24        6295
25        6671
26        8522
27        8994
28        9113
29        9125
         ...  
1857    685987
1858    686437
1859    686636
1860    687565
1861    687642
1862    687909
1863    687941
1864    687941
1865    688011
1866    688031
1867    688037
1868    688519
1869    688567
1870    688574
1871    688660
1872    688697
1873    688708
1874    688731
1875    689956
1876    690781
1877    690789
1878    691912
1879    691912
1880    692222
1881    692487
1882    692578
1883    692579
1884    693083
1885    694194
1886    695367
Name: index, Length: 1887, dtype: int64

## Load in Data

In [3]:
corpus = []
corpus_path = glob.glob("/Users/charlesmarshall/Desktop/IEMS 308/Project 3/*/*.txt")

for file_path in corpus_path:
    with open(file_path,encoding='ISO-8859-1') as f_input:
        #reviews_train.append(open(os.path.join(pos_path,file),'rb').read().decode('utf-8'))
        corpus.append(f_input.read())

In [10]:
corpus_test = []
test_path = glob.glob("/Users/charlesmarshall/Desktop/IEMS 308/Project 3/2014/*.txt")

for file_path in test_path:
    with open(file_path,encoding='ISO-8859-1') as f_input:
        corpus_test.append(f_input.read())

## Clean data

Remove all unicode and *.

In [4]:
print(corpus[0])

ReutersChina's seven day repo rose to a record high of 10.77% in Shanghai, the highest since March 2003, according to Bloomberg*. Meanwhile, the one-day rate hit a record 12.85%. And Zerohedge reported that overnight repo hit 25%. The liquidity squeeze in China first began ahead of the Dragon Boat festival earlier this month. Spikes in interbank rates are common right before holidays.  But Diana Choyleva at Lombard Street Research said this is symptomatic of a bigger problem. She said capital flows had "become a more important driver of domestic liquidity conditions in China's managed exchange rate system." In a new note to clients Bank of America's Ting Lu wrote: "There are many factors behind the interbank liquidity squeeze that might be cited, but we believe that the ultimate reason is the central bank’s tough stance as the PBOC can practically provide unlimited liquidity to ease every squeeze if it wishes to."  Banks have been clamoring for a reserve requirement ratio cut. So w

In [6]:
for text in range(len(corpus)):
    corpus[text] = re.sub(r'[^\x00-\x7f]|[*]',r'', corpus[text])

In [7]:
print(corpus[0])

ReutersChina's seven day repo rose to a record high of 10.77% in Shanghai, the highest since March 2003, according to Bloomberg. Meanwhile, the one-day rate hit a record 12.85%. And Zerohedge reported that overnight repo hit 25%. The liquidity squeeze in China first began ahead of the Dragon Boat festival earlier this month. Spikes in interbank rates are common right before holidays. But Diana Choyleva at Lombard Street Research said this is symptomatic of a bigger problem. She said capital flows had "become a more important driver of domestic liquidity conditions in China's managed exchange rate system." In a new note to clients Bank of America's Ting Lu wrote: "There are many factors behind the interbank liquidity squeeze that might be cited, but we believe that the ultimate reason is the central banks tough stance as the PBOC can practically provide unlimited liquidity to ease every squeeze if it wishes to." Banks have been clamoring for a reserve requirement ratio cut. So why isn't

## Tokenize to Sentences

In [27]:
docs = []

for text in range(len(corpus)):
    s = sent_tokenize(corpus[text])
    docs.append(s)

In [28]:
len(docs)

730

In [29]:
docs = [item for sublist in docs for item in sublist]

In [30]:
len(docs)

695841

In [31]:
docs[6940]

'Crablike, Mr Hollande is trying to do just enough on Europe, without aggravating nationalism at home.'

## Remove stopwords

This is mainly done to make sure candidate answers match the disctionary value

In [290]:
stop_words=sorted(set(stopwords.words("english")))

In [291]:
def drop_stop_words(ls):
    for i in range(len(ls)):
        tokenized_sent = word_tokenize(ls[i])
        ls[i] = ' '.join([word for word in tokenized_sent if word.lower() not in stop_words])
        
    return ls;

In [292]:
docs = drop_stop_words(docs)

In [294]:
docs[6940]

'Crablike , Mr Hollande trying enough Europe , without aggravating nationalism home .'

## TD-IDF Matrix

In [295]:
def identity(x):
    return x

tf = TfidfVectorizer()
tfidf_mat = tf.fit_transform(docs)

In [296]:
tfidf_mat

<695841x165385 sparse matrix of type '<class 'numpy.float64'>'
	with 8352567 stored elements in Compressed Sparse Row format>

In [298]:
# Column index in which the word exists in
tf.vocabulary_

{'reuterschina': 123098,
 'seven': 131182,
 'day': 43336,
 'repo': 121746,
 'rose': 125359,
 'record': 120030,
 'high': 70307,
 '10': 618,
 '77': 7270,
 'shanghai': 131583,
 'highest': 70333,
 'since': 133572,
 'march': 92104,
 '2003': 2633,
 'according': 9453,
 'bloomberg': 25628,
 'meanwhile': 94191,
 'one': 105997,
 'rate': 118890,
 'hit': 70818,
 '12': 995,
 '85': 7739,
 'zerohedge': 164863,
 'reported': 121780,
 'overnight': 108176,
 '25': 3530,
 'liquidity': 88742,
 'squeeze': 137345,
 'china': 34240,
 'first': 57727,
 'began': 22990,
 'ahead': 11553,
 'dragon': 48573,
 'boat': 26024,
 'festival': 56755,
 'earlier': 49685,
 'month': 97838,
 'spikes': 136793,
 'interbank': 77655,
 'rates': 118928,
 'common': 37328,
 'right': 124225,
 'holidays': 71135,
 'diana': 45894,
 'choyleva': 34575,
 'lombard': 89393,
 'street': 139563,
 'research': 122206,
 'said': 126772,
 'symptomatic': 142040,
 'bigger': 24395,
 'problem': 115749,
 'capital': 31163,
 'flows': 58748,
 'become': 22722,
 'i

In [299]:
tfidf_mat[0,131182]

0.2524818769312878

In [302]:
# IDF scores of each word in the matrix
tf.idf_[131182]

7.046167171873654

## Read in Question

## Scoring Algorithm

Calculating the score of a candidate sentence based on two dimensions:
    
    1) The number of matched bigrams between a question and a candidate sentence
    2) The TD-IDF score between a question and candidate sentence
    
The score of the two dimensions are added together to create the overall score for each candidate.

In [405]:
def score_algo(question,answer):
    # Bigrams
    question_lower = question.lower()
    answer_lower = answer.lower()
    question_lower_words = question_lower.split(' ')
    answer_lower_words = answer_lower.split(' ')
    
    # NEED TO REMOVE STOP WORDS FROM QUESTION
    question_words = question.split(' ')
    answer_words = answer.split(' ')
    bigrams_question = set([b for b in zip(question_words[:-1], question_words[1:])])
    bigrams_answer = set([b for b in zip(answer_words[:-1], answer_words[1:])])
    match_bigrams = bigrams_question.intersection(bigrams_answer)
    bigram_score =  len(match_bigrams)
    
    # TD-IDF Matched
    common_words = set(question_lower_words).intersection(answer_lower_words);
    #Find column indexes in TFIDF matrix:
    common_words = list(common_words)
    col_index = []
    # ONLY CURRENTLY WORKS FOR LOWERCASE
    for i in common_words: col_index.append(tf.vocabulary_[i])
    if answer in row_index:
        row = row_index[answer]
    else:
        return "Error: Candidate answer not in CEO set"
    score_matched = []
    for i in col_index: score_matched.append(tfidf_mat[row,i])
    tfidf_matched = sum(score_matched)
    
    # TF-IDF Non-Matched (Missing)
    missing_words = np.setdiff1d(question_lower_words,answer_lower_words,assume_unique=True)
    tfidf_question = tf.fit_transform(question_lower_words)
    missing_index = []
    for i in missing_words: missing_index.append(tf.vocabulary_[i])
    score_missing = []
    for i in missing_index: score_missing.append(tfidf_question[0,i])
    tfidf_missing = sum(score_missing)
    
    # Overall Score
    score = bigram_score + tfidf_matched - tfidf_missing;
    return score

In [404]:
score_algo('Who is the ceo of BATS', docs[1157])

[5, 2, 4, 3]

In [392]:
docs[1157]

"BATS CEO Joe Ratterman told Wall Street Journal problems `` part business exchange electronic environment '' ."

In [377]:
def question_preprocess(question):
    if question[-1] == '?':
        question = question[0:len(question)-1]
    
    tokenized_sent = word_tokenize(question)
    question = ' '.join([word for word in tokenized_sent if word.lower() not in stop_words])
    
    return question

In [378]:
question_preprocess('Who is the CEO of BATS?')

'CEO BATS'

## CEO's

### Steps:

    1) Choose a subset of sentences - I'm going to consider all senetences that I have identified to have CEOs in them based on last week's assignment.
    2) Input the question.
    3) Run each sentence through the scoring algorithm compared to a question. Scoring algorithm has basically already been created but need to arrange things so that the question is inputted and everything is processed correctly including capitals and ...
    4) Output the name of the CEO in the sentence with the highest score.
    

In [303]:
ceo_index = ceo_final['index']

In [304]:
ceo_final

Candidate  length  sent_len  caps  sent_caps  who  \
0              Joe Ratterman      13       110     2         12  0.0   
1             Square Capital      14       214     2         13  0.0   
2                Third Point      11       194     2         24  0.0   
3           Former Citigroup      16       139     2          8  0.0   
4                Sandy Weill      11       139     2          8  0.0   
5               Bank America      12       118     2          8  0.0   
6             Warren Buffett      14       102     2          8  0.0   
7         Berkshire Hathaway      18       173     2          7  0.0   
8       Bloomberg Television      20       141     2         11  0.0   
9           Capital Advisors      16       139     2         14  0.0   
10               Mike Ullman      11        68     2          8  0.0   
11          Capital Advisors      16       104     2         10  0.0   
12               Ron Johnson      11       151     2         11  0.0   
13                  Best Buy       8       611     2         15  0.0   
14                 Elon Musk       9        78     2          9  0.0   
15               Scott Davis      11        62     2          8  0.0   
16            Square Capital      14       283     2         59  0.0   
17              Alan Mulally      12       134     2          6  0.0   
18               Wall Street      11       131     2          5  0.0   
19             Goldman Sachs      13       159     2          9  0.0   
20           John Hammergren      15       160     2         11  0.0   
21            Ellison Oracle      14       162     2         13  0.0   
22             Credit Suisse      13        81     2          7  0.0   
23               Jamie Dimon      11       277     2         30  0.0   
24             Global Cities      13       265     2         28  0.0   
25         Capital Financial      17       165     2         17  0.0   
26               Jamie Dimon      11        96     2          8  0.0   
27          Capital Advisors      16       140     2         15  0.0   
28               Ron Johnson      11       120     2         19  0.0   
29               Ron Johnson      11        61     2         16  0.0   
...                      ...     ...       ...   ...        ...  ...   
1857        Skymark Airlines      16       258     2         21  0.0   
1858         Lloyd Blankfein      15       361     2         29  0.0   
1859            Dick Costolo      12        72     2          6  0.0   
1860          Heather Bresch      14       224     2         13  0.0   
1861             Mike Perlis      11       314     2         20  0.0   
1862             Les Moonves      11        63     2         11  0.0   
1863              Ford Motor      10       197     2         11  0.0   
1864            Alan Mulally      12       197     2         11  0.0   
1865           Satay Nadella      13        89     2          6  0.0   
1866            Bank America      12        83     2         12  0.0   
1867            Bank America      12       125     2          8  0.0   
1868           John Chambers      13       127     2          7  0.0   
1869           John Chambers      13        57     2          6  0.0   
1870           John Chambers      13        32     2          8  0.0   
1871           John Chambers      13        95     2          9  0.0   
1872          Jayshree Ullal      14        33     2          7  0.0   
1873           John Chambers      13        29     2         10  0.0   
1874           Masayoshi Son      13       208     2         15  0.0   
1875          Aleksey Miller      14       128     2          8  0.0   
1876          Michael Corbat      14        81     2          6  0.0   
1877           Mark Karpeles      13       228     2         20  0.0   
1878            Jim Chambers      12       207     2         11  0.0   
1879  Watchers International      22       207     2         11  0.0   
1880            Daniel Baker      12        80     2       

In [305]:
ceo_candidates = ceo_final[['index','Candidate','Sentence']]
ceo_candidates

index               Candidate  \
0       1157           Joe Ratterman   
1       1354          Square Capital   
2       1896             Third Point   
3       1980        Former Citigroup   
4       1980             Sandy Weill   
5       1988            Bank America   
6       2144          Warren Buffett   
7       2148      Berkshire Hathaway   
8       2505    Bloomberg Television   
9       3379        Capital Advisors   
10      3401             Mike Ullman   
11      3408        Capital Advisors   
12      3600             Ron Johnson   
13      3641                Best Buy   
14      3650               Elon Musk   
15      4034             Scott Davis   
16      4072          Square Capital   
17      4081            Alan Mulally   
18      4203             Wall Street   
19      4204           Goldman Sachs   
20      4555         John Hammergren   
21      5848          Ellison Oracle   
22      6161           Credit Suisse   
23      6293             Jamie Dimon   
24      6295           Global Cities   
25      6671       Capital Financial   
26      8522             Jamie Dimon   
27      8994        Capital Advisors   
28      9113             Ron Johnson   
29      9125             Ron Johnson   
...      ...                     ...   
1857  685987        Skymark Airlines   
1858  686437         Lloyd Blankfein   
1859  686636            Dick Costolo   
1860  687565          Heather Bresch   
1861  687642             Mike Perlis   
1862  687909             Les Moonves   
1863  687941              Ford Motor   
1864  687941            Alan Mulally   
1865  688011           Satay Nadella   
1866  688031            Bank America   
1867  688037            Bank America   
1868  688519           John Chambers   
1869  688567           John Chambers   
1870  688574           John Chambers   
1871  688660           John Chambers   
1872  688697          Jayshree Ullal   
1873  688708           John Chambers   
1874  688731           Masayoshi Son   
1875  689956          Aleksey Miller   
1876  690781          Michael Corbat   
1877  690789           Mark Karpeles   
1878  691912            Jim Chambers   
1879  691912  Watchers International   
1880  692222            Daniel Baker   
1881  692487           Reed Hastings   
1882  692578               Named New   
1883  692579             Time Warner   
1884  693083               John Wren   
1885  694194             Jamie Dimon   
1886  695367         Lloyd Blankfein   

                                               Sentence  
0     BATS CEO Joe Ratterman told Wall Street Journa...  
1     's full release Pershing : William A. Ackman ,...  
2     SEE ALSO : seen major turning point fight tril...  
3     Former Citigroup CEO Sanford Sandy Weill said ...  
4     Former Citigroup CEO Sanford Sandy Weill said ...  
5     Bank America CEO Brian T. Moynihan said hes co...  
6     Sokol Berkshire Hathaway subsidiary executive ...  
7     weeks resignation , Berkshire Hathaway CEO mad...  
8     tend little positive Im hearing people , 58-ye...  
9     Brian Sozzi , CEO Belus Capital Advisors point...  
10    meddling JCP CEO Mike Ullman focused beginning...  
11    `` 's still core Baby Boomer customer change b...  
12    began Pershing Square Capital 's Bill Ackman m...  
13    Stockahrts.com three paragraphs today 's earni...  
14    Tesla MotorsHere 's another extraordinary acco...  
15    best tidbit issue comes bizarre exchange UPS C...  
16    PEGCC PEGCC PEGCC PEGCC PEGCC PEGCC Reuters/ S...  
17    hybrid result , according Ford CEO Alan Mulall...  
18    Wall Street CEO something like , people would ...  
19    , Goldman Sachs CEO Lloyd Blankfein conference...  
20    may also set record corporate America $ 159 mi...  
21    Societe Generale Oracle 's annual meeting Thur...  
22    turns Credit Suisse 's CEO Brady Dougan , 53 ,...  
23    Atlantic Cities : Radical Case Bloomberg 's 'N...  
24    Dimon London series JPM events , anchored CEO ...  
25    Three Ways A

In [306]:
row_index = {}
for i in range(len(ceo_index)):
    row_index[docs[ceo_index[i]]] = ceo_index[i]

In [324]:
docs[115741]

"JC Penney CEO : Ron Johnson ( still CEO end FY ending 2012 ) CEO employee pay ratio : 1,795 ( $ 53.3 million/ $ 29,688 ) Abercrombie & amp ; Fitch Co. CEO : Michael Jeffries CEO employee pay ratio : 1,640 ( $ 53.3 million/ $ 29,688 ) Simon Property Group CEO : David Simon CEO employee pay ratio : 1,594 ( $ 137.2 million/ $ 86,003 ) FY ended 2011 Oracle Corp. CEO : Larry Ellison CEO employee pay ratio : 1,287 ( $ 96.2 million/ $ 74,693 ) Starbucks CEO : Howard Schultz CEO employee pay ratio : 1,135 ( $ 28.9 million/ $ 25,463 ) CBS Corp. CEO : Leslie Moonves CEO employee pay ratio : 1,111 ( $ 69.9 million/ $ 62,930 ) FY ended 2011 Ralph Lauren Corp. CEO : Ralph Lauren CEO employee pay ratio : 1,083 ( $ 36.3 million/ $ 33,550 ) Nike CEO : Mark Parker CEO employee pay ratio : 1,050 ( $ 35.2 million/ $ 33,550 ) companies argue bulk CEO compensation form long-term stock options give incentives perform well work shareholders , others 's necessary keep top leaders leaving competitor ."

In [426]:
def ceo_question():
    question = input("Please enter your question in the form 'Who is the CEO of company X?':\n")
    question = question_preprocess(question)
    sent_score = []
    for i in ceo_candidates['Sentence']:
        sent_score.append(score_algo(question,i))
    ceo_candidates['sent_score'] = sent_score
    ceo_sort =  ceo_candidates.sort_values(by=['sent_score'], ascending=False).reset_index(drop=True)
    return ceo_sort
    print("The CEO of the company is: {}" .format(ceo_sort['Candidate'][0]))

In [437]:
ceo_question()

Please enter your question in the form 'Who is the CEO of company X?':
Who is the Gilead CEO?


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


index             Candidate  \
0     685039           John Martin   
1     342537            Pete Flint   
2       9125           Ron Johnson   
3     544709          Michael Weil   
4     502521         Beauty Wealth   
5     505854      Nash Wealthfront   
6     505479       Klaus Kleinfeld   
7     505475  Morris International   
8     505272         Marissa Mayer   
9     505272            Jeff Bezos   
10    505272    Billionaire Amazon   
11    505182             Elon Musk   
12    504838           Paul Wright   
13    502897           Jamie Dimon   
14    502685           Vegas Sands   
15    502521     Shareholder Value   
16    502123          Dick Costolo   
17    507007        Kasper Rorsted   
18    502114         Ginni Rometty   
19    501790       Mark Zuckerberg   
20    501704       Mark Zuckerberg   
21    501485    Lourenco Goncalves   
22    500387       Michael Pearson   
23    500010        Square Capital   
24    499723              Tim Cook   
25    499600         Emilio Lozoya   
26    498264        Brian Moynihan   
27    498141              Robin Li   
28    498135          Michael Dell   
29    498134             Net Worth   
...      ...                   ...   
1857  295585         Merrill Lynch   
1858  296282         Belus Capital   
1859  307680             Mike Duke   
1860  296444           Mike Ullman   
1861  306846            Jack Welch   
1862  306735         Marissa Mayer   
1863  306629             Elon Musk   
1864  306499             Elon Musk   
1865  306368      Steve Schwarzman   
1866  306147        Research Group   
1867  306147           Sam Barnett   
1868  306141             Elon Musk   
1869  305969        Severin Schwan   
1870  304984          Aaron Regent   
1871  304806          Credit Lance   
1872  303654       Lloyd Blankfein   
1873  303654          Take Goldman   
1874  302356            Wear Daily   
1875  302356           Ron Johnson   
1876  301212        Gabaix Landier   
1877  300906    Highbridge Capital   
1878  299749           Dutch Shell   
1879  299474               Post Co   
1880  298860         Cloud Foundry   
1881  298135  Caterpillar Chairman   
1882  298001           Steve Cohen   
1883  297765          Bank America   
1884  297012           Jason Cheng   
1885  296993     Fairfax Financial   
1886  695367       Lloyd Blankfein   

                                               Sentence  sent_score  
0     company 's earnings release , Gilead CEO John ...    1.143834  
1     Conference Call Discuss Acquisition 9 a.m. EDT...   -0.694719  
2     around 5:00 PM ET , CNBC reported Ron Johnson ...   -0.695058  
3     RCAP Executives Putting Money Mouth ( Wealth M...   -0.848895  
4     `` Beauty Wealth : CEO Appearance Shareholder ...   -1.000000  
5     Writes president CEO Adam Nash Wealthfront blo...   -1.000000  
6     `` transaction bring together greatest innovat...   -1.000000  
7     `` 2014 proving complex truly atypical year , ...   -1.000000  
8     examples : Billionaire Amazon founder Jeff Bez...   -1.000000  
9     examples : Billionaire Amazon founder Jeff Bez...   -1.000000  
10    examples : Billionaire Amazon founder Jeff Bez...   -1.000000  
11    Tesla CEO Elon Musk called `` fool cells '' co...   -1.000000  
12    `` conditions exist particularly innortheast G...   -1.000000  
13    Morgan CEO Jamie Dimon ( front ) leaves U.S. J...   -1.000000  
14    puts squarely fellow billionaire Sheldon Adels...   -1.000000  
15    `` Beauty Wealth : CEO Appearance Shareholder ...   -1.000000  
16    Rometty worked directly Twitter CEO Dick Costo...   -1.000000  
17    `` expect escalation Russian Ukrainian conflic...   -1.000000  
18    IBM CEO Ginni Rometty vision dominate next hig...   -1.000000  
19    Rick Wilking/ReutersFacebook CEO Mark Zuckerbe...   -1.000000  
20    Rick Wilking/ReutersFacebook CEO Mark Zuckerbe...   -1.000000  
21    FREE AppDownload Cliffs NaturalCliffs Natural ...   -1.000000  
22    `` disappointed hand , think deal 

In [435]:
ceo_question()

Please enter your question in the form 'Who is the CEO of company X?':
Who is the CEO of Tesla?


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


index              Candidate  \
0     658345              Elon Musk   
1     342537             Pete Flint   
2       9125            Ron Johnson   
3     544709           Michael Weil   
4       1157          Joe Ratterman   
5     502521      Shareholder Value   
6     505854       Nash Wealthfront   
7     505479        Klaus Kleinfeld   
8     505475   Morris International   
9     505272          Marissa Mayer   
10    505272             Jeff Bezos   
11    505272     Billionaire Amazon   
12    505182              Elon Musk   
13    504838            Paul Wright   
14    502897            Jamie Dimon   
15    502685            Vegas Sands   
16    502521          Beauty Wealth   
17    507007         Kasper Rorsted   
18    502123           Dick Costolo   
19    502114          Ginni Rometty   
20    501790        Mark Zuckerberg   
21    501704        Mark Zuckerberg   
22    501485     Lourenco Goncalves   
23    500387        Michael Pearson   
24    500010         Square Capital   
25    499723               Tim Cook   
26    499600          Emilio Lozoya   
27    498264         Brian Moynihan   
28    498141               Robin Li   
29    498135           Michael Dell   
...      ...                    ...   
1857  298860          Cloud Foundry   
1858  303654        Lloyd Blankfein   
1859  303654           Take Goldman   
1860  305969         Severin Schwan   
1861  306147         Research Group   
1862  302356            Ron Johnson   
1863  301212         Gabaix Landier   
1864  300906     Highbridge Capital   
1865  299749            Dutch Shell   
1866  299474                Post Co   
1867  304984           Aaron Regent   
1868  411757         Blake Mycoskie   
1869  411757             Mark Cuban   
1870  147042           Nelson Peltz   
1871  597783             Carl Icahn   
1872  428215            Daniel Loeb   
1873  147042       Delivering Alpha   
1874    1896            Third Point   
1875  343653          Romero Belize   
1876  407458         Blake Mycoskie   
1877  407458             Mark Cuban   
1878  407454             Mark Cuban   
1879  675712         Blake Mycoskie   
1880   74992             David Karp   
1881  675712             Mark Cuban   
1882   35138  Relations Abercrombie   
1883   35138  Relations Abercrombie   
1884  358114         Leon Cooperman   
1885  411753             Mark Cuban   
1886  263725    Chief Restructuring   

                                               Sentence  sent_score  
0     Elon Musk CEO Tesla chairman Solar City , 's s...    1.000000  
1     Conference Call Discuss Acquisition 9 a.m. EDT...    0.305281  
2     around 5:00 PM ET , CNBC reported Ron Johnson ...    0.304942  
3     RCAP Executives Putting Money Mouth ( Wealth M...    0.151105  
4     BATS CEO Joe Ratterman told Wall Street Journa...    0.000000  
5     `` Beauty Wealth : CEO Appearance Shareholder ...    0.000000  
6     Writes president CEO Adam Nash Wealthfront blo...    0.000000  
7     `` transaction bring together greatest innovat...    0.000000  
8     `` 2014 proving complex truly atypical year , ...    0.000000  
9     examples : Billionaire Amazon founder Jeff Bez...    0.000000  
10    examples : Billionaire Amazon founder Jeff Bez...    0.000000  
11    examples : Billionaire Amazon founder Jeff Bez...    0.000000  
12    Tesla CEO Elon Musk called `` fool cells '' co...    0.000000  
13    `` conditions exist particularly innortheast G...    0.000000  
14    Morgan CEO Jamie Dimon ( front ) leaves U.S. J...    0.000000  
15    puts squarely fellow billionaire Sheldon Adels...    0.000000  
16    `` Beauty Wealth : CEO Appearance Shareholder ...    0.000000  
17    `` expect escalation Russian Ukrainian conflic...    0.000000  
18    Rometty worked directly Twitter CEO Dick Costo...    0.000000  
19    IBM CEO Ginni Rometty vision dominate next hig...    0.000000  
20    Rick Wilking/ReutersFacebook CEO Mark Zuckerbe...    0.000000  
21    Rick Wilking/ReutersFacebook CEO Mark Zuck

In [432]:
docs[255374]

'points make blurriness : Evening Standard Sam Palmisano excellent CEO IBM .'

In [433]:
ceo_question()

Please enter your question in the form 'Who is the CEO of company X?':
Who is the Apple CEO?


/Users/charlesmarshall/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


index           Candidate  \
0     403468            Tim Cook   
1     267815            Tim Cook   
2     608464          Carl Ichan   
3     608464            Tim Cook   
4     499723            Tim Cook   
5     530353            Tim Cook   
6      35133            Tim Cook   
7     267933            Tim Cook   
8     267922            Tim Cook   
9     267922          Carl Icahn   
10    628469            Tim Cook   
11    165359            Tim Cook   
12    391461            Tim Cook   
13    628469          Carl Icahn   
14     26608            Tim Cook   
15    125701          Carl Icahn   
16    396158            Tim Cook   
17    227616            Tim Cook   
18    125701            Tim Cook   
19    125892            Tim Cook   
20    111102            Tim Cook   
21    165363            Tim Cook   
22    684016            Tim Cook   
23    583783            Tim Cook   
24    648002            Tim Cook   
25    359154            Tim Cook   
26     82798            Tim Cook   
27    654158            Tim Cook   
28    365727            Tim Cook   
29    187536           Time Cook   
...      ...                 ...   
1857  289279    Starbucks Howard   
1858  302356         Ron Johnson   
1859  303654        Take Goldman   
1860  314977         Ron Johnson   
1861  308392        Former Enron   
1862  313827       Kirana Airbus   
1863  313720         Sandy Weill   
1864  313423     Robert Reynolds   
1865  311964           Tom Joyce   
1866  311648        Dick Costolo   
1867  309965    Business Insider   
1868  309711  Committee Preserve   
1869  309475     Lloyd Blankfein   
1870  309475        Take Goldman   
1871  308579        Former Enron   
1872  308432       Jeff Skilling   
1873  307680           Mike Duke   
1874  303654     Lloyd Blankfein   
1875  306846          Jack Welch   
1876  306735       Marissa Mayer   
1877  306629           Elon Musk   
1878  306499           Elon Musk   
1879  306368    Steve Schwarzman   
1880  306147      Research Group   
1881  306147         Sam Barnett   
1882  306141           Elon Musk   
1883  305969      Severin Schwan   
1884  304984        Aaron Regent   
1885  304806        Credit Lance   
1886  695367     Lloyd Blankfein   

                                               Sentence  sent_score  
0     Leon Cooperman also spoke Apple , live Carl Ic...         1.0  
1     Cramer 's argument Icahn 's favor Apple CEO Ti...         1.0  
2     Billionaire investor Carl Ichan wrote open let...         1.0  
3     Billionaire investor Carl Ichan wrote open let...         1.0  
4     Apple CEO Tim Cook said conference call analys...         1.0  
5     Apple CEO Tim Cook Samsung CEOOh-Hyun Kwonwill...         1.0  
6     discussed magnitude '' Icahn referring Apple C...         1.0  
7     second issue happened yesterday reminder Apple...         1.0  
8     happened yesterday , case missed , famous inve...         1.0  
9     happened yesterday , case missed , famous inve...         1.0  
10    FREE AppDownload time Valentine 's Day , billi...         1.0  
11    Icahn says bought billion dollars worth Apple ...         1.0  
12    investors fortunate position ( thanks comments...         1.0  
13    FREE AppDownload time Valentine 's Day , billi...         1.0  
14    April , Apple CEO Tim Cook apologised changed ...         1.0  
15    Billionaire activist investor Carl Icahn grabb...         1.0  
16    Apple CEO Tim Cook predicted upgrade would tri...         1.0  
17    Read full piece Bloomberg & gt ; Business Insi...         1.0  
18    Billionaire activist investor Carl Icahn grabb...         1.0  
19    Watch segment via South China Morning Post : J...         1.0  
20    last public presentations , Apple CEO Tim Cook...         1.0  
21    Apple CEO Tim Cook much better things spend ev...         1.0  
22    BI 's Jim Edwards characterized Apple CEO Tim ...         1.0  
23    Next release : February 24 , 2014 's 's looked...         1.0  
24    Though Apple Pay l